apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: files-converter-app
spec:
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: divakar51/files-converter-api-gateway:0.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: api-gateway-config-map
