apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
  namespace: files-converter-app
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
