apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  namespace: files-converter-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: divakar51/files-converter-auth:0.0.1
        resources:
          limits:
            memory: "120Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: auth-service-config-map
