apiVersion: v1
kind: Service
metadata:
  name: auth-service-svc
  namespace: files-converter-app
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
    protocol: TCP
